### ISSUE TITLE
Test suite doesn't compile with aeson 2.0

### ISSUE THREAD

**Issue by sternenseemann** [monadfix/shower#17]
```
[1 of 2] Compiling Property         ( tests/Property.hs, dist/build/shower-tests/shower-tests-tmp/Property.o, dist/build/shower-tests/shower-tests-tmp/Property.dyn_o )

tests/Property.hs:20:20: error:
    • Couldn't match type ‘HashMap.HashMap Text.Text Aeson.Value’
                     with ‘Data.Aeson.KeyMap.KeyMap Aeson.Value’
      Expected type: [(Text.Text, Aeson.Value)] -> Aeson.Object
        Actual type: [(Text.Text, Aeson.Value)]
                     -> HashMap.HashMap Text.Text Aeson.Value
    • In the second argument of ‘(.)’, namely ‘HashMap.fromList’
      In the first argument of ‘(<$>)’, namely
        ‘Aeson.Object . HashMap.fromList’
      In the expression:
        Aeson.Object . HashMap.fromList
          <$>
            resize
              (size `div` 2)
              (listOf ((,) <$> (Text.pack <$> arbitrary) <*> genJSON))
   |
20 |     Aeson.Object . HashMap.fromList <$>
   |                    ^^^^^^^^^^^^^^^^
```
